# DeltaOrb Configuration
coins_value: 15

# Ki Density Settings
kidensity:
  min: -50
  max: 50
  time: 600
  levels:
    1:
      min_players: 5
      max_players: 9
      min_density: -25
      max_density: 50
    2:
      min_players: 10
      max_players: 14
      min_density: 0
      max_density: 50
    3:
      min_players: 15
      max_players: 19
      min_density: 15
      max_density: 60
      vip_max_density: 85
    4:
      min_players: 20
      max_players: 29
      min_density: 25
      max_density: 75
      vip_max_density: 100
    5:
      min_players: 30
      max_players: 39
      min_density: 35
      max_density: 85
      vip_max_density: 120
    6:
      min_players: 40
      max_players: 59
      min_density: 40
      max_density: 95
      vip_max_density: 130
    7:
      min_players: 60
      max_players: 80
      min_density: 50
      max_density: 105
      vip_max_density: 145

# Event Settings
evento2x: true

# VIP Boosts: permission;tag;boost;color
vip_boosts:
  - permission: yt.sk
    tag: YT
    boost: 15
    color: "&c"
  - permission: prime.sk
    tag: PRIME
    boost: 25
    color: "&3"
  - permission: streamer.sk
    tag: STREAMER
    boost: 15
    color: "&d"
  - permission: suporte.sk
    tag: SUPORTE
    boost: 10
    color: "&b"
  - permission: vip.sk
    tag: VIP
    boost: 35
    color: "&e"
  - permission: vip+.sk
    tag: VIP+
    boost: 50
    color: "&6"
  - permission: mvp.sk
    tag: MVP
    boost: 85
    color: "&b"
  - permission: mvp+.sk
    tag: MVP+
    boost: 125
    color: "&d"
  - permission: delta.sk
    tag: DELTA
    boost: 180
    color: "&f"

# Random Orb Items
random_orbs:
  - "159"
  - "159:1"

# Database Settings
database:
  host: localhost
  port: 3306
  database: deltaorb
  username: root
  password: ""
  pool-size: 10